### ISSUE TITLE
New-ZipEntry Fails if File Being Added is > 2 GB

### ISSUE THREAD

**Issue by franklesniak** [santisq/PSCompression#19]
As the title says, New-ZipEntry fails with an error "Stream was too long." when adding a file larger than 2 GB to an existing archive.

Example command:

```powershell
New-ZipEntry -Destination '.\Folder\ZipFile.zip' -EntryPath 'VeryLargeFile.csv' -SourcePath (Join-Path $env:temp 'VeryLargeFile.csv') -CompressionLevel ([System.IO.Compression.CompressionLevel]::SmallestSize)
```

Issue encountered on PowerShell version 7.3.8 on Windows 11.

**Comment by santisq** [comment]
Hi @franklesniak thanks for submitting this issue, I think this might be the same issue discussed in #5 and if so, unfortunately I don't have a solution for this as its an issue with the .NET API being used behind the scenes.

**Comment by franklesniak** [comment]
Oh, interesting. As a workaround, I must delete and recreate the ZIP file. Got it, makes sense!

**Comment by santisq** [comment]
@franklesniak yeah, unfortunately it's the same issue and it's been around since 2016: https://github.com/dotnet/runtime/issues/1544... the best advise I could give you is to use 7zip if you need to add new Zip Entries to an existing Zip Archive or recreated the Zip Archive :(
