### ISSUE TITLE
`Compress-ZipArchive` still hits 2GB limit when using `-Update`

### ISSUE THREAD

**Issue by ssilvidi** [santisq/PSCompression#5]
Running into the same issue as referenced here: https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/19#issuecomment-1398329745

> I've just tried this on a 3.7GB file and it cuts the original file short as the CopyTo has the same Stream was too long issue. The archive completes but only with 2GB of the original file.

I found this module in hopes of solving a strange case where I've only got remote PowerShell access to a server and I need to compress some big log files. I don't have enough free space to compress the entire folder, so my plan was to add a few files at a time to the archive. 

Unfortunately, I'm getting the usual "Stream was too long" error when using `-Update`. Note that I don't have a problem when creating a new archive - it only seems to happen with `-Update`.

```powershell
PS E:\Services\logs\AppService> ls *2023-03-0*.svclog | select -First 3


    Directory: E:\Services\logs\AppService


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         3/4/2023  11:59 PM      899010559 AppServiceLog-2023-03-04-00-00-01.svclog
-a----         3/5/2023  11:59 PM     5206177620 AppServiceLog-2023-03-05-00-00-00.svclog
-a----         3/6/2023   5:47 PM     3460504997 AppServiceLog-2023-03-06-00-00-01.svclog

...

PS E:\Services\logs\AppService> ls *2023-03-0*.svclog | select -First 3 | Compress-ZipArchive -DestinationPath $dest -Update
Compress-ZipArchive : Exception calling "CopyTo" with "1" argument(s): "Stream was too long."
At line:1 char:43
+ ...  select -First 3 | Compress-ZipArchive -DestinationPath $dest -Update
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Compress-ZipArchive], MethodInvocationException
    + FullyQualifiedErrorId : IOException,Compress-ZipArchive

Compress-ZipArchive : Exception calling "CopyTo" with "1" argument(s): "Stream was too long."
At line:1 char:43
+ ...  select -First 3 | Compress-ZipArchive -DestinationPath $dest -Update
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Compress-ZipArchive], MethodInvocationException
    + FullyQualifiedErrorId : IOException,Compress-ZipArchive

...

PS E:\Services\logs\AppService> $archive = [System.IO.Compression.ZipFile]::OpenRead("$pwd\AppServiceLog_backup_2023-03-21.zip")
PS E:\Services\logs\AppService> $archive.Entries | ft fullname, compressedlength, length

FullName                                 CompressedLength     Length
--------                                 ----------------     ------
AppServiceLog-2023-02-18-00-00-00.svclog         11079552  862175799
AppServiceLog-2023-02-25-00-00-00.svclog         12047838  970221159
AppServiceLog-2023-03-04-00-00-01.svclog         11284310  899010559
AppServiceLog-2023-03-05-00-00-00.svclog         28428997 2147450880
AppServiceLog-2023-03-06-00-00-01.svclog         29660913 2147450880

```

This was with PSCompression 1.0.4 from PSGallery and PowerShell 5.1.17763.2931.
Hopefully the output above tells the story, but let me know what I can do to help. 

Thanks!

**Comment by santisq** [comment]
Hi @ssilvidi will test this later but looking at the .NET Docs the exception you might be seeing is this one:

![image](https://user-images.githubusercontent.com/23342410/226681837-10e2f30a-61de-46f9-8241-9614cbbeeb4c.png)


In which case I'm afraid I don't have a solution for this.

**Comment by ssilvidi** [comment]
Thanks for the quick response!

I was able to make it work in my scenario by creating separate archives in a few steps. Like you said, creating new files worked for me regardless of the size.
